---
title: "DataGeneration.R"
author: "Baris Uzel"
date: "January 23, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Weekly Assignment - Week 3


##load packages in to R
```{r}
library(dplyr)
```


##Generate dataset
```{r}
Species <- c("Vulpes lagopus", "Canis arctos", "Rangifer tarandus", "Alces alces", "Ovis dalli", "Ovibus moschatus", "Ursus maritimus", "Enhydra lutris", "Gulo gulo", "Lepus arcticus") # generate species data

Limb.Width <- rnorm(10,mean=10,sd=10) # generate limb width data
print(Limb.Width)
Limb.Width <- abs(Limb.Width) #convert lw to absolute value
print(Limb.Width) #make sure it works

unitsW <- rbinom(10,size=1,prob=0.5) #generate units by binomial distr of 0.5 chance
unitsW <- ifelse(unitsW > 0, "mm", "cm") #change probability names to unit names
print(unitsW)


Limb.Length <- rnorm(10,mean=100,sd=100) # generate limb length data
print(Limb.Length)
Limb.Length <- abs(Limb.Length)
print(Limb.Length)

unitsL <- rbinom(10,size=1,prob=0.5) #generate units
unitsL <- ifelse(unitsL > 0, "mm", "cm")
print(unitsL)

MyData <- data.frame(Species, Limb.Width, unitsW, Limb.Length, unitsL)

write.csv(MyData, file = "measurements.csv")
```

